# Welcome {.unnumbered}

This book is an introduction to Data Science for Psychologists (and others in the social sciences). Primarily using the **R programming language**, you will learn a general workflow that helps you to process, plot, analyse, and present data to your audience. It is expected that readers are familiar with introductory statistics typically taught at the Undergraduate level in Psychology programmes across the UK.

Throughout, concepts will be taught using examples from real and simulated data from studies in Psychology. R will be taught using a **tidyverse**-first approach, using a suite of packages that are designed to make programming quick, easy, and highly readable.

## Sections

### Core

The first section of the book is written for those with **no experience with R or programming** in general. The focus here is on using R across the data processing and analysis pipeline so that you can automate data processing. This has the benefit of documenting your work, automating tedious manual processes, and avoiding user error. Along the way, you will learn about best practices in terms of project structure and workflows, version control to track and manage updates to your code, and how to share your work online with the broader scientific community. By the end of this section you should be able to do all your data analysis work with R.

### Advanced

The second section of the book is written for those with a background in R or who have completed the core content who want to take advantage of the advanced data analysis methods available to this language. This section has a heavier focus on theory with the goal of understanding not just how to use advanced methods, but also how these methods work, how to diagnose and solve problems, and how to communicate your findings.

## Course Content

To download the course content, including workshop slides, videos, and exercise workbooks, including instructions for using and downloading the content, please follow this link: <https://github.com/gpwilliams/ds-psych_course>
